browser=edge
password=secret_sauce
url=https://www.saucedemo.com/
user=standard_user
orangeHrmUser=Admin
orangeHrmlPassword=admin123
orangeHrmUrl=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login